### ISSUE TITLE
对进攻吞食这种规则我的一些看法

### ISSUE THREAD

**Issue by poplar-xirolan** [pkulab409/sessdsa.2048#1]
#### Pros
- 进攻吞食时，每个人都肯定会把最大的棋子放在交界线处（某些zz AI除外），假设A方处于优势时，可以把对面的大棋子吞了，对面逆转的可能性很小
- 这样能营造出针锋相对的氛围，从气氛上就很不错
- 不过吞食时自己的点数也需要减少一部分，不然拿着个4096就gank全场了

#### Cons
- 容易造成AI算法的单一化，即前期拼命刷点，后期疯狂进攻
- 向对方指定棋盘扔方块的决策大概就固化在围最大的块这么一个思路了，很容易超时

**Comment by Vittorio-Veneto-www** [comment]
说的很对，但我怎么觉得写的全是Cons呢（
进攻吞食的话，有这样的设想，比如要花费一定代价，献祭棋子之类的，这些也可以考虑进去

**Comment by SophieARG** [comment]
谢谢反馈！~~什么？这个回复太官方？不存在的~~
