### ISSUE TITLE
对数据接口的讨论

### ISSUE THREAD

**Issue by CastleStar14654** [pkulab409/sessdsa.2048#3]
**更新**
1. 传随机位置可以有，但确实不是很有绝对的必要性。好处可能也就是方便队伍自查吧。
但确实可以在维持接口统一性的前提下多传些可能用到的参数
2. currentRound靠接口传参等方式维护同步为宜
3. 是的，现在这个issue的标题和内容毫无关系了

~~现在的接口方案是在初始化时给两个Player传进随机序列array
https://github.com/pkulab409/sessdsa.2048/blob/master/src/player.py#L16:#L18
然后每一回合由Player和Platform各自***独立***计算当前步骤的可行位置。
Player的：
https://github.com/pkulab409/sessdsa.2048/blob/master/src/player.py#L99:#L109
Platform的：
https://github.com/pkulab409/sessdsa.2048/blob/master/src/plat.py#L316:#L330
是否有可能将接口改为`output_position(self, random_offer)`，随机位置仅由Platform计算一次，然后实时传给决策方？这样子仍然符合目前规则，而且能够避免各方有可能出现的对随机位置计算结果不一的尴尬问题。~~

当然，如果现有接口这样设计是为了使各队伍有能力预测之后***多轮***回合的走向、甚至预测对方的随机位置的话，我也十分赞成。

~~PS:
此外，现有接口是通过向双方***传递操作***来实现的，但这样子相当于所有队伍都要实现一波从操作到棋盘战局的转化。是否有可能将接口换成***传递实时棋盘***呢？（也许是想桃子）比方说:~~
```
             self.next = self.get_next(0)                    # 按照随机序列得到下一个位置
            self.position[0] = self.player[0].output_position(repr(self), self.next)
            if self.checkTime(0): break                     # 判断是否超时
            self.log.append('&d player 0 set position %s' % str(self.position[0]))
            if self.checkViolate(0, 'position'): break      # 判断是否违规
            self.update(0, 'position')                      # 更新棋盘 
            self.log.append('&p\n' + self.__repr__())
            
            self.next = self.get_next(1)                    # 按照随机序列得到下一个位置
            self.position[1] = self.player[1].output_position(repr(self), self.next)
            if self.checkTime(1): break                     # 判断是否超时
            self.log.append('&d player 1 set position %s' % str(self.position[1]))
            if self.checkViolate(1, 'position'): break      # 判断是否违规
            self.update(1, 'position')                      # 更新棋盘 
            self.log.append('&p\n' + self.__repr__())
            
            self.direction[0] = self.player[0].output_direction(repr(self))
            if self.checkTime(0): break                     # 判断是否超时
            self.log.append('&d player 0 set direction %s' % str(self.direction[0]))
            self.update(0, 'direction')                     # 更新棋盘
            if self.checkViolate(0, 'direction'): break     # 判断是否违规
            self.log.append('&p\n' + self.__repr__())
            
            self.direction[1] = self.player[1].output_direction(repr(self))
            if self.checkTime(1): break                     # 判断是否超时
            self.log.append('&d player 1 set direction %s' % str(self.direction[1]))
            self.update(1, 'direction')                     # 更新棋盘
            if self.checkViolate(1, 'direction'): break     # 判断是否违规
            self.log.append('&p\n' + self.__repr__())
```
~~其中`repr(self)`是将当前战局以字符串形式传给`player`。~~

**Comment by Vittorio-Veneto-www** [comment]
之所以要给出确定的序列，就是为了消除随机因素，确保以后的局势是可预测的，ai的编写中也可以考虑到这一因素
不搞传递实时棋盘而是传递操作，是为了让ai程序能够判断对方的风格，预判操作，将来也许会给出一些基本的ai类型作为参考。如果不想搞预判的骚操作，也可直接利用样例的恢复局面方法
实际上，就以实现来说，你提出的方法反而更容易；现在这么做是为了增加ai编写的可能性

**Comment by CastleStar14654** [comment]
> 实际上，之所以要给出确定的序列，就是为了消除随机因素，确保以后的局势是可预测的，ai的编写中也可以考虑到这一因素

确实，提前给序列提供了更多的工作空间，我也赞同保留提前给序列的方式；但这也并不与在`output_position`中实时传递当前生成的随机位置矛盾。同样的操作platform和player都要跑一遍总还是比较emm
> 不搞传递实时棋盘而是传递操作，是为了让ai程序能够判断对方的风格，预判操作，将来也许会给出一些基本的ai类型作为参考。如果不想搞预判的骚操作，也可直接利用样例的恢复局面方法

好有道理 (手动捂脸)。传棋盘的话各队也还是得写个解析棋盘的东西hhh，还是直接给操作直接。 
但接口拆成input和output真的有必要吗……`__init__()`里既然已经给定先手后手，那么input与output的对应关系就已经确定了。似乎保留两个output就够了（传进来的是position还是direction可以通过tuple还是int区分）

**Comment by Vittorio-Veneto-www** [comment]
现在程序也还处于初步的开发阶段，有些地方会逐步优化，比如output等
后面平台可能会提供标准的接口函数以实现传递随机序列和操作表，以及对棋盘和随机序列的计算。当然这些都还没开始做（也许吧，看开发平台的yh大佬心情

**Comment by SophieARG** [comment]
感谢反馈！~~最近一段时间因为Sophie和gal已经很久没干活了~~

---
作为开发者，我想从当初player的接口设计用意来回答一下你提出的问题。
* **为什么选择让参赛队伍自行维护棋盘？**
你提出的实时传递棋盘其实是我最开始的考虑，因为传递实时棋盘显然有利于参赛队伍把重点放在对抗算法的设计上，而不必再写```platform```中本来就有的有些繁杂的落子和合并算法；同时，也使得时间限制更加充裕，代码更加精简。但是，最后选择传递具体操作，这主要基于三点理由：
   * 增强ai的适应性。这个理由在讨论中已经提到了，如果传递棋盘，必然要和ai约定棋盘的传递格式（字符串、二维列表、坐标字典等），这也就意味着ai要编写针对**特定平台**的解析方法，这样使得ai对不同平台的适应性较低，也使得开发者对平台的修改可能影响ai的正常运行。
   * 尽可能增加ai编写的自由。一个接口方案应该尽可能做到**黑盒化**，这样会给实现者留下尽可能大的发挥空间。在这里，ai与平台的交流仅仅用两个```input```和两个```output```实现，这意味着参赛队伍的棋盘、棋子等完全由自己维护，所以可以采用**最适合己方对抗算法**的设计方案——这一点，在通过平台限制维护方式的前提下就算做到，也可能会因格式转换而耗费不必要的代价——而且考虑到有些队伍可能拥有比标准维护方式更优的设计，而这也应该是一个优质ai的能力体现。
   * 减少不必要的开销。如果选择传入棋盘，每次都要调用解析方法，这样也会带来核心算法之外的时间开销；更重要的是，某些队伍可能因算法需要而已经维护了棋盘，在这种情况下前面的时间开销完全无益。

   其实，模版ai已经提供了一种设计思路，借鉴起来也并非难事。所以我认为这个接口方案对参赛队伍的开发难度也不会有多大助长。当然，这方面我们还可以继续讨论，听听大家的意见。
* **为什么拆成```input```和```output```？**
这个主要是基于：
   * 代码可读性。四个方法简明易懂（~~至少我觉得~~），好理解，我写注释也方便。
   * 可扩展性。因为规则还没有确定下来，为了尽可能保证可扩展性，我的代码设计都是**基元化**的。如果把```input```直接绑定到```output```里面，至少像“连下两子”这种规则拓展实现起来稍显困难（~~更不要说什么献祭操作~~）。

   不过，你的方案对代码行的精简是很有效的；在规则确定了以后，会考虑这个建议。届时就算```player```已经编写完毕，也是很好修改的。
* **为什么不实时传递随机位置？**
说实话，这个设计的理由并不像之前两个那么充足，甚至我自己都认为是不理想的方案。这次我采用的是**实现```init_process(self, array)```方法+事先约定算法+维护```currentRound```属性**的方案。为了防止计算出的随机位置不同而**要求参赛队伍维护当前轮数属性**这一点是最大的缺点，对代码风格、选手自由度等等的损害都很大。但是选择这种方案，我考虑的和你分析的一样，即**不能限制参赛队伍对多轮结果的综合预测**。如果每次都传入随机位置，相当于强制队伍“鼠目寸光”，这和我们的规则设计理念是不符的。为了鼓励大家“高瞻远瞩”，似乎把计算随机位置的算法预载进ai里是一个好的选择？
这一点，我想听听大家的意见。下一次的主要修改大概就是这个方面的，因为我也对目前的实现方法非常不满。只是，现在供我选择的都不是很好的方案。

---
**再次感谢你的建议，很有参考价值。**
但是因为本人很咸的缘故，所以会鸽多久也不知道。
~~别问，问就在做了在做了~~
![sticker (22)](https://user-images.githubusercontent.com/62552868/78691400-25072000-792b-11ea-802f-c4c7eb7967b2.png)

**Comment by CastleStar14654** [comment]
> 这次我采用的是实现`init_process(self, array)`方法+事先约定算法+维护`currentRound`属性的方案。为了防止计算出的随机位置不同而要求参赛队伍维护当前轮数属性这一点是最大的缺点，对代码风格、选手自由度等等的损害都很大。

所以我觉得可以既使用`init_process(self, array)`，又向选手传实时的随机位置。这对平台来说并没有增加什么负担，但可以减少选手的一小部分运算量，也可以给选手一个测验自己这边这个**事先约定的随机位置生成算法**有没有正确工作的方式

**Comment by SophieARG** [comment]
> 所以我觉得可以既使用init_process(self, array)，又向选手传实时的随机位置

这个意思是说，让参赛队伍再实现一个方法```input_available(self, row, column)```接受下一个随机位置吗？我感觉好像这样并没有解决本质上的问题……**如果参赛队伍要在ai里自己计算随机的位置，就应该和平台共享当前轮数**。而这个共享是要求```currentRound```属性存在的（要不然把这个属性也改成一个方法？）：因为主平台有很多的终局方式，所以ai自带的轮数更新方法可能来不及调用，那么在胜者继续游戏的时候就需要强行同步，也就是这行代码做的事情：
https://github.com/pkulab409/sessdsa.2048/blob/master/src/plat.py#L293
所以，增加```input_available(self, row, column)```除了让队伍多一个要实现的方法以外，我看不到还有什么很大的价值（而且对需要自己计算的队伍来说反而是无意义的死代码），至少感觉在核心问题上没有起到特别大的作用。

---
补充：的确可以减少一点计算量，不过这个计算量应该不会有特别大的影响吧（？）

**Comment by Vittorio-Veneto-www** [comment]
我觉得他的意思是平台只负责调用ai而不传入信息，至于ai需要什么信息，由ai调用平台的方法来获取……

**Comment by SophieARG** [comment]
> 我觉得他的意思是平台只负责调用ai而不传入信息，至于ai需要什么信息，由ai调用平台的方法来获取……

<ruby>什么，这到底是什么控制流<rt>何それ、意味わかないよ</rt></ruby>

**Comment by CastleStar14654** [comment]
> 而这个共享是要求`currentRound`属性存在的（要不然把这个属性也改成一个方法？）：因为主平台有很多的终局方式，所以ai自带的轮数更新方法可能来不及调用，那么在胜者继续游戏的时候就需要强行同步，也就是这行代码做的事情：
> https://github.com/pkulab409/sessdsa.2048/blob/master/src/plat.py#L293

 emm，发现这是个更大的问题。目前 @HamiltonHuaji 写的 [secureclass](https://github.com/pkulab409/sessdsa.2048/blob/master/src/secureclass.py) 为了安全性只实现了方法的转发；属性转发没有实现。同时，如果实现属性转发，ai是可以利用property装饰器之类的在属性赋值的时候搞事情的。
————还是靠方法和传参最保守最明了 ( x

> 让参赛队伍再实现一个方法`input_available(self, row, column)`接受下一个随机位置吗？

并不需要加一个接口啊。当且仅当调用`output_position()`的时候需要传随机位置，那么将随机位置作为参数传给`output_position()`就好了。 
同理，`currentRound`也完全可以作为***参数传递***、同步，而不是靠客户和平台**各自维护**一个属性。

> 我觉得他的意思是平台只负责调用ai而不传入信息，至于ai需要什么信息，由ai调用平台的方法来获取……

（这个”他“指我吗）允许ai调用平台的话就会涉及双方交互……还是现在这种轮询比较方便技术组吧（咦

> 什么，这到底是什么控制流

-------------------------------------
假装总结一发（这个issue好像歪到不知道哪里去了）

1. 共同维护`currentRound`属性可能比较糟糕，传参可能更稳妥一些
2. 平台算的很多东西可以靠传参的方式给ai

**Comment by SophieARG** [comment]
> 同理，currentRound也完全可以作为参数传递、同步，而不是靠客户和平台各自维护一个属性。

每次调用```output```的时候都同步一遍吗？虽然直接，这倒也是一个办法……

![sticker (12)](https://user-images.githubusercontent.com/62552868/78739694-675e4a80-7987-11ea-8d2b-c21932d5a072.png)

只是随机位置什么的真的有传的必要吗，如果可以自己算出来……如果可以的话，我其实希望功能函数的参数列表尽可能简洁的。~~你已经是一个成熟的ai了，该学会自己计算随机位置了.jpg~~

**Comment by CastleStar14654** [comment]
【删去强行论证。传随机位置可以有，但不是很有绝对的必要性】 
另外，多传点参实际上并不会有多大坏处吧（可能除了”丑“这一点hhh，但接口系统化的话也还好。传不可变对象也能够保证安全性）毕竟传给用户的参数用户可以不用，但用户想要的、平台算过的参数却还得自己算一遍确实挺糟心的 ( x

---------------------------------
我现在的point就是建议别依靠维护属性来同步吧，比方说：
https://github.com/pkulab409/sessdsa.2048/blob/master/src/plat.py#L293:#L296
你真的能信任294行里面ai给出的行数吗？
【我现在不觉得传随机位置是必要的，虽然如果传的话确实是好的】

**Comment by SophieARG** [comment]
已经按照讨论修改过了。
![-6](https://user-images.githubusercontent.com/62552868/79235002-a287de80-7e9d-11ea-809a-aea35e0ad7c7.jpg)

**Comment by Vittorio-Veneto-www** [comment]
经过陈老师的教育，platform现在会给ai传棋盘（
